<a href="https://colab.research.google.com/github/AndreeAguilar/-Examen1/blob/main/Examen1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [3]:
#Carga desde un archivos
data1=pd.read_excel('consumer_mit_lift_lab.xlsx') 
data2=pd.read_excel('microretailer_mit_lift_lab.xlsx') 
data3=pd.read_csv('lastmile_delivery_operations_mit_lift_lab.csv') 
data4=pd.read_csv('lastmile_delivery_operations_mit_lift_lab_serving_customer.csv')

Consumer_mit_lift_lab

In [4]:
# Aplicamos filtro para separar datos.
filtro_cuantitativo=data1.iloc[ : , [5,6,12,26,27,28,29,30,31]]
filtro_cuantitativo

,_latitude,_longitude,238_frequency_buying_store,81_number_online_purchases_month,288_number_app_purchases_month,289_number_whatsapp_purchases_month,83_willingness_ultrafast_delivery,84_willingness_sameday_delivery,241_age_of_the_interviewee
0,19.059841,-98.234980,1,1,0,0,0,0,35
1,19.058479,-98.233566,1,1,2,0,35,50,27
2,19.062077,-98.230339,1,0,0,0,40,25,42
3,19.055535,-98.232916,1,2,3,0,0,0,27
4,19.059012,-98.232994,1,2,5,0,0,50,35
...,...,...,...,...,...,...,...,...,...
110,19.035224,-98.267100,1,15,10,0,100,100,15
111,19.035280,-98.267856,1,1,1,0,50,70,21
112,19.035451,-98.267862,1,3,2,0,0,0,18
113,19.035486,-98.267831,1,2,4,0,30,100,18
114,19.035399,-98.267924,1,0,3,0,150,1000,18

In [5]:
filtro_cualitativo=data1.iloc[ : , [0,1,2,3,4,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,32,33,34]]
filtro_cualitativo

,_record_id,_title,_server_updated_at,_updated_by,_geometry,282_payment_method_that_purchase,283_fulfill_needs,300_did_not_find,237_distance_household_interviewee,299_means_transportation_consumer,...,307_gas_bill_store,286_topups,308_topups_in_store,287_wire_transfers,309_wiretransfers_in_store,320_other_services_in_store,304_additional_services_store,240_gender_interviewee,indicate_the_type_of_store,name_of_the_store
0,060a856c-e3b8-41a7-b680-9756172d1c29,"November 12, 2022",2022-11-12 22:43:08 UTC,Ulises Núñez Bautista,SRID=4326;POINT(-98.2349802856 19.0598413203),Efectivo,no,agua de coco,0 a 3 cuadras,A pie,...,no,No lo hago,no,Banco,no,no,NaN,Male,Cafeteria,Paleteria El Carmen
1,c42fdf22-b93b-443e-8f46-6043613cb0c3,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2335660729 19.05847939),Efectivo,yes,NaN,7 a 10 cuadras,A pie,...,no,Tienda de conveniencia (e.g. OXXO),no,Banco,no,no,NaN,Female,Grocery store (aka. nanostore),Gerardo Saénz
2,3ccaedc0-949e-4555-afad-b2e1d77c3219,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2303385023 19.0620767997),Efectivo,yes,NaN,más de 10 cuadras,Automóvil,...,yes,"Supermercado,Tienda de conveniencia (e.g. OXXO)",yes,Banco,no,no,NaN,Female,Micro-restaurant (aka. fondita),Rozt
3,91d8a240-af2c-451b-900f-3480f82e05db,"November 12, 2022",2022-11-12 20:41:38 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329163449 19.0555346049),Tarjeta de débito y/o crédito,yes,NaN,4 a 6 cuadras,Motocicleta,...,no,No lo hago,no,Banco,no,no,NaN,Female,Cafeteria,Café Colibrí
4,3efefc56-bd45-4e4a-bf02-ab725e9fb41a,"November 12, 2022",2022-11-12 19:49:13 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329944224 19.0590117522),Efectivo,yes,NaN,más de 10 cuadras,Transporte público,...,no,Supermercado,no,No lo hago,no,no,NaN,Female,Cafeteria,La fête
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,ee7ac407-4767-47b1-93b3-d7e09b49faec,"November 3, 2022",2022-11-03 20:15:32 UTC,Daniel Serrano,SRID=4326;POINT(-98.2671002671 19.0352236761),Efectivo,yes,NaN,20 min,Automóvil,...,no,No lo hago,no,No lo hago,no,no,NaN,Male,Micro-restaurant (aka. fondita),Taquería don Jorge
111,f65a8190-df80-440e-83bc-2639decfffd0,"November 3, 2022",2022-11-03 20:05:31 UTC,Daniel Serrano,SRID=4326;POINT(-98.2678556442 19.0352804088),Efectivo,yes,NaN,30 min,Transporte público,...,no,No lo hago,no,No lo hago,no,no,NaN,Female,Cafeteria,La parrilla del lobo
112,70f42238-83b5-4a16-9f2e-a758efb8afb0,"November 3, 2022",2022-11-03 20:04:35 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678617 19.0354511),Efectivo,yes,NaN,0 a 3 cuadras,A pie,...,no,Tienda de conveniencia (e.g. OXXO),no,No lo hago,no,no,NaN,Male,Cafeteria,La Parrilla del lobo
113,e4727f46-797f-4344-b183-0deeed11750f,"November 3, 2022",2022-11-03 20:04:34 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678314 19.0354858),Efectivo,yes,NaN,más de 10 cuadras,Didi,...,no,Tienda de conveniencia (e.g. OXXO),no,No lo hago,no,no,NaN,Male,Cafeteria,Crudopolis
114,0a5616e1-62cd-4f28-a282-9b34db145752,"November 3, 2022",2022-11-03 19:58:24 UTC,Daniel Serrano,SRID=4326;POINT(-98.2679243758 19.0353989453),Efectivo,yes,NaN,4 a 6 cuadras,Transporte público,...,no,No lo hago,no,No lo hago,no,no,NaN,Male,Cafeteria,Crudopolis

In [6]:
#Corroboramos valores nulos de los datos
valores_nulos=filtro_cuantitativo.isnull().sum()
valores_nulos

_latitude                              0
_longitude                             0
238_frequency_buying_store             0
81_number_online_purchases_month       0
288_number_app_purchases_month         0
289_number_whatsapp_purchases_month    0
83_willingness_ultrafast_delivery      0
84_willingness_sameday_delivery        0
241_age_of_the_interviewee             0
dtype: int64

In [7]:
valores_nulos=filtro_cualitativo.isnull().sum()
valores_nulos

_record_id                              0
_title                                  0
_server_updated_at                      0
_updated_by                             0
_geometry                               0
282_payment_method_that_purchase        0
283_fulfill_needs                       0
300_did_not_find                      109
237_distance_household_interviewee      0
299_means_transportation_consumer       0
284_additional_products_store         111
301_electricity_bill                    0
305_electricity_bill_store              7
302_water_bill                          0
306_water_bill_store                    4
303_gas_bill                            0
307_gas_bill_store                      3
286_topups                              0
308_topups_in_store                    12
287_wire_transfers                      0
309_wiretransfers_in_store              2
320_other_services_in_store             0
304_additional_services_store          86
240_gender_interviewee                  0
indicate_the_type_of_store              0
name_of_the_store                       0
dtype: int64

In [8]:
#Sustituimos vn por un texto.
filtro_cualitativo["300_did_not_find"]=filtro_cualitativo["300_did_not_find"].fillna("NA")
filtro_cualitativo["284_additional_products_store"]=filtro_cualitativo["284_additional_products_store"].fillna("NA")
filtro_cualitativo["304_additional_services_store"]=filtro_cualitativo["304_additional_services_store"].fillna("NA")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [9]:
#Reemplazamos valores nulos restantes con bfill
filtro_cualitativo=filtro_cualitativo.fillna(method="bfill") 
filtro_cualitativo

,_record_id,_title,_server_updated_at,_updated_by,_geometry,282_payment_method_that_purchase,283_fulfill_needs,300_did_not_find,237_distance_household_interviewee,299_means_transportation_consumer,...,307_gas_bill_store,286_topups,308_topups_in_store,287_wire_transfers,309_wiretransfers_in_store,320_other_services_in_store,304_additional_services_store,240_gender_interviewee,indicate_the_type_of_store,name_of_the_store
0,060a856c-e3b8-41a7-b680-9756172d1c29,"November 12, 2022",2022-11-12 22:43:08 UTC,Ulises Núñez Bautista,SRID=4326;POINT(-98.2349802856 19.0598413203),Efectivo,no,agua de coco,0 a 3 cuadras,A pie,...,no,No lo hago,no,Banco,no,no,NA,Male,Cafeteria,Paleteria El Carmen
1,c42fdf22-b93b-443e-8f46-6043613cb0c3,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2335660729 19.05847939),Efectivo,yes,NA,7 a 10 cuadras,A pie,...,no,Tienda de conveniencia (e.g. OXXO),no,Banco,no,no,NA,Female,Grocery store (aka. nanostore),Gerardo Saénz
2,3ccaedc0-949e-4555-afad-b2e1d77c3219,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2303385023 19.0620767997),Efectivo,yes,NA,más de 10 cuadras,Automóvil,...,yes,"Supermercado,Tienda de conveniencia (e.g. OXXO)",yes,Banco,no,no,NA,Female,Micro-restaurant (aka. fondita),Rozt
3,91d8a240-af2c-451b-900f-3480f82e05db,"November 12, 2022",2022-11-12 20:41:38 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329163449 19.0555346049),Tarjeta de débito y/o crédito,yes,NA,4 a 6 cuadras,Motocicleta,...,no,No lo hago,no,Banco,no,no,NA,Female,Cafeteria,Café Colibrí
4,3efefc56-bd45-4e4a-bf02-ab725e9fb41a,"November 12, 2022",2022-11-12 19:49:13 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329944224 19.0590117522),Efectivo,yes,NA,más de 10 cuadras,Transporte público,...,no,Supermercado,no,No lo hago,no,no,NA,Female,Cafeteria,La fête
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,ee7ac407-4767-47b1-93b3-d7e09b49faec,"November 3, 2022",2022-11-03 20:15:32 UTC,Daniel Serrano,SRID=4326;POINT(-98.2671002671 19.0352236761),Efectivo,yes,NA,20 min,Automóvil,...,no,No lo hago,no,No lo hago,no,no,NA,Male,Micro-restaurant (aka. fondita),Taquería don Jorge
111,f65a8190-df80-440e-83bc-2639decfffd0,"November 3, 2022",2022-11-03 20:05:31 UTC,Daniel Serrano,SRID=4326;POINT(-98.2678556442 19.0352804088),Efectivo,yes,NA,30 min,Transporte público,...,no,No lo hago,no,No lo hago,no,no,NA,Female,Cafeteria,La parrilla del lobo
112,70f42238-83b5-4a16-9f2e-a758efb8afb0,"November 3, 2022",2022-11-03 20:04:35 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678617 19.0354511),Efectivo,yes,NA,0 a 3 cuadras,A pie,...,no,Tienda de conveniencia (e.g. OXXO),no,No lo hago,no,no,NA,Male,Cafeteria,La Parrilla del lobo
113,e4727f46-797f-4344-b183-0deeed11750f,"November 3, 2022",2022-11-03 20:04:34 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678314 19.0354858),Efectivo,yes,NA,más de 10 cuadras,Didi,...,no,Tienda de conveniencia (e.g. OXXO),no,No lo hago,no,no,NA,Male,Cafeteria,Crudopolis
114,0a5616e1-62cd-4f28-a282-9b34db145752,"November 3, 2022",2022-11-03 19:58:24 UTC,Daniel Serrano,SRID=4326;POINT(-98.2679243758 19.0353989453),Efectivo,yes,NA,4 a 6 cuadras,Transporte público,...,no,No lo hago,no,No lo hago,no,no,NA,Male,Cafeteria,Crudopolis

In [10]:
#Corroboramos valores nulos
valores_nulos=filtro_cualitativo.isnull().sum()
valores_nulos

_record_id                            0
_title                                0
_server_updated_at                    0
_updated_by                           0
_geometry                             0
282_payment_method_that_purchase      0
283_fulfill_needs                     0
300_did_not_find                      0
237_distance_household_interviewee    0
299_means_transportation_consumer     0
284_additional_products_store         0
301_electricity_bill                  0
305_electricity_bill_store            0
302_water_bill                        0
306_water_bill_store                  0
303_gas_bill                          0
307_gas_bill_store                    0
286_topups                            0
308_topups_in_store                   0
287_wire_transfers                    0
309_wiretransfers_in_store            0
320_other_services_in_store           0
304_additional_services_store         0
240_gender_interviewee                0
indicate_the_type_of_store            0
name_of_the_store                     0
dtype: int64

In [11]:
#Método por cuartiles 0.25 y 0.75
y=filtro_cuantitativo

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _latitude                               19.137956
_longitude                             -98.025979
238_frequency_buying_store               6.000000
81_number_online_purchases_month         6.000000
288_number_app_purchases_month          12.500000
289_number_whatsapp_purchases_month      2.500000
83_willingness_ultrafast_delivery      102.500000
84_willingness_sameday_delivery        231.250000
241_age_of_the_interviewee              65.000000
dtype: float64
Limite inferior permitido _latitude                               18.959124
_longitude                             -98.402770
238_frequency_buying_store              -2.000000
81_number_online_purchases_month        -2.000000
288_number_app_purchases_month          -7.500000
289_number_whatsapp_purchases_month     -1.500000
83_willingness_ultrafast_delivery      -37.500000
84_willingness_sameday_delivery       -118.750000
241_age_of_the_interviewee              -7.000000
dtype: float64

In [12]:
#Encontramos valores atípicos.
outliers_iqr=filtro_cuantitativo[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr

,_latitude,_longitude,238_frequency_buying_store,81_number_online_purchases_month,288_number_app_purchases_month,289_number_whatsapp_purchases_month,83_willingness_ultrafast_delivery,84_willingness_sameday_delivery,241_age_of_the_interviewee
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
110,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,150.0,1000.0,NaN

In [13]:
#Encontramos datos limpios.
data3_iqr=filtro_cuantitativo[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

,_latitude,_longitude,238_frequency_buying_store,81_number_online_purchases_month,288_number_app_purchases_month,289_number_whatsapp_purchases_month,83_willingness_ultrafast_delivery,84_willingness_sameday_delivery,241_age_of_the_interviewee
0,19.059841,-98.234980,1.0,1.0,0.0,0.0,0.0,0.0,35.0
1,19.058479,-98.233566,1.0,1.0,2.0,0.0,35.0,50.0,27.0
2,19.062077,-98.230339,1.0,0.0,0.0,0.0,40.0,25.0,42.0
3,19.055535,-98.232916,1.0,2.0,3.0,0.0,0.0,0.0,27.0
4,19.059012,-98.232994,1.0,2.0,5.0,0.0,0.0,50.0,35.0
...,...,...,...,...,...,...,...,...,...
110,19.035224,-98.267100,1.0,NaN,10.0,0.0,100.0,100.0,15.0
111,19.035280,-98.267856,1.0,1.0,1.0,0.0,50.0,70.0,21.0
112,19.035451,-98.267862,1.0,3.0,2.0,0.0,0.0,0.0,18.0
113,19.035486,-98.267831,1.0,2.0,4.0,0.0,30.0,100.0,18.0
114,19.035399,-98.267924,1.0,0.0,3.0,0.0,NaN,NaN,18.0

In [14]:
#Corroboramos vn del dataframe limpio.
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

_latitude                               0
_longitude                              0
238_frequency_buying_store              2
81_number_online_purchases_month        9
288_number_app_purchases_month          4
289_number_whatsapp_purchases_month    19
83_willingness_ultrafast_delivery      10
84_willingness_sameday_delivery         3
241_age_of_the_interviewee              4
dtype: int64

In [15]:
#Hacemos una copia del dataframe.
#Reemplazamos valores atípicos con mean.
data5_iqr=data3_iqr.copy()
data5_iqr=data5_iqr.fillna(round(data3_iqr.mean(),1))
data5_iqr

,_latitude,_longitude,238_frequency_buying_store,81_number_online_purchases_month,288_number_app_purchases_month,289_number_whatsapp_purchases_month,83_willingness_ultrafast_delivery,84_willingness_sameday_delivery,241_age_of_the_interviewee
0,19.059841,-98.234980,1.0,1.0,0.0,0.0,0.0,0.0,35.0
1,19.058479,-98.233566,1.0,1.0,2.0,0.0,35.0,50.0,27.0
2,19.062077,-98.230339,1.0,0.0,0.0,0.0,40.0,25.0,42.0
3,19.055535,-98.232916,1.0,2.0,3.0,0.0,0.0,0.0,27.0
4,19.059012,-98.232994,1.0,2.0,5.0,0.0,0.0,50.0,35.0
...,...,...,...,...,...,...,...,...,...
110,19.035224,-98.267100,1.0,1.8,10.0,0.0,100.0,100.0,15.0
111,19.035280,-98.267856,1.0,1.0,1.0,0.0,50.0,70.0,21.0
112,19.035451,-98.267862,1.0,3.0,2.0,0.0,0.0,0.0,18.0
113,19.035486,-98.267831,1.0,2.0,4.0,0.0,30.0,100.0,18.0
114,19.035399,-98.267924,1.0,0.0,3.0,0.0,35.1,56.9,18.0

In [16]:
#Sumamos los datos cuantitativos y los datos cualitativos.
Datos_limpios_consumer_mit_lift_lab = pd.concat([filtro_cualitativo, data5_iqr], axis=1)
Datos_limpios_consumer_mit_lift_lab

,_record_id,_title,_server_updated_at,_updated_by,_geometry,282_payment_method_that_purchase,283_fulfill_needs,300_did_not_find,237_distance_household_interviewee,299_means_transportation_consumer,...,name_of_the_store,_latitude,_longitude,238_frequency_buying_store,81_number_online_purchases_month,288_number_app_purchases_month,289_number_whatsapp_purchases_month,83_willingness_ultrafast_delivery,84_willingness_sameday_delivery,241_age_of_the_interviewee
0,060a856c-e3b8-41a7-b680-9756172d1c29,"November 12, 2022",2022-11-12 22:43:08 UTC,Ulises Núñez Bautista,SRID=4326;POINT(-98.2349802856 19.0598413203),Efectivo,no,agua de coco,0 a 3 cuadras,A pie,...,Paleteria El Carmen,19.059841,-98.234980,1.0,1.0,0.0,0.0,0.0,0.0,35.0
1,c42fdf22-b93b-443e-8f46-6043613cb0c3,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2335660729 19.05847939),Efectivo,yes,NA,7 a 10 cuadras,A pie,...,Gerardo Saénz,19.058479,-98.233566,1.0,1.0,2.0,0.0,35.0,50.0,27.0
2,3ccaedc0-949e-4555-afad-b2e1d77c3219,"November 12, 2022",2022-11-12 22:15:02 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2303385023 19.0620767997),Efectivo,yes,NA,más de 10 cuadras,Automóvil,...,Rozt,19.062077,-98.230339,1.0,0.0,0.0,0.0,40.0,25.0,42.0
3,91d8a240-af2c-451b-900f-3480f82e05db,"November 12, 2022",2022-11-12 20:41:38 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329163449 19.0555346049),Tarjeta de débito y/o crédito,yes,NA,4 a 6 cuadras,Motocicleta,...,Café Colibrí,19.055535,-98.232916,1.0,2.0,3.0,0.0,0.0,0.0,27.0
4,3efefc56-bd45-4e4a-bf02-ab725e9fb41a,"November 12, 2022",2022-11-12 19:49:13 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.2329944224 19.0590117522),Efectivo,yes,NA,más de 10 cuadras,Transporte público,...,La fête,19.059012,-98.232994,1.0,2.0,5.0,0.0,0.0,50.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,ee7ac407-4767-47b1-93b3-d7e09b49faec,"November 3, 2022",2022-11-03 20:15:32 UTC,Daniel Serrano,SRID=4326;POINT(-98.2671002671 19.0352236761),Efectivo,yes,NA,20 min,Automóvil,...,Taquería don Jorge,19.035224,-98.267100,1.0,1.8,10.0,0.0,100.0,100.0,15.0
111,f65a8190-df80-440e-83bc-2639decfffd0,"November 3, 2022",2022-11-03 20:05:31 UTC,Daniel Serrano,SRID=4326;POINT(-98.2678556442 19.0352804088),Efectivo,yes,NA,30 min,Transporte público,...,La parrilla del lobo,19.035280,-98.267856,1.0,1.0,1.0,0.0,50.0,70.0,21.0
112,70f42238-83b5-4a16-9f2e-a758efb8afb0,"November 3, 2022",2022-11-03 20:04:35 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678617 19.0354511),Efectivo,yes,NA,0 a 3 cuadras,A pie,...,La Parrilla del lobo,19.035451,-98.267862,1.0,3.0,2.0,0.0,0.0,0.0,18.0
113,e4727f46-797f-4344-b183-0deeed11750f,"November 3, 2022",2022-11-03 20:04:34 UTC,Fernando Gonzálezinactivo,SRID=4326;POINT(-98.2678314 19.0354858),Efectivo,yes,NA,más de 10 cuadras,Didi,...,Crudopolis,19.035486,-98.267831,1.0,2.0,4.0,0.0,30.0,100.0,18.0
114,0a5616e1-62cd-4f28-a282-9b34db145752,"November 3, 2022",2022-11-03 19:58:24 UTC,Daniel Serrano,SRID=4326;POINT(-98.2679243758 19.0353989453),Efectivo,yes,NA,4 a 6 cuadras,Transporte público,...,Crudopolis,19.035399,-98.267924,1.0,0.0,3.0,0.0,35.1,56.9,18.0

In [17]:
#Corroboramos valores nulos.
valores_nulos=Datos_limpios_consumer_mit_lift_lab.isnull().sum()
valores_nulos

_record_id                             0
_title                                 0
_server_updated_at                     0
_updated_by                            0
_geometry                              0
282_payment_method_that_purchase       0
283_fulfill_needs                      0
300_did_not_find                       0
237_distance_household_interviewee     0
299_means_transportation_consumer      0
284_additional_products_store          0
301_electricity_bill                   0
305_electricity_bill_store             0
302_water_bill                         0
306_water_bill_store                   0
303_gas_bill                           0
307_gas_bill_store                     0
286_topups                             0
308_topups_in_store                    0
287_wire_transfers                     0
309_wiretransfers_in_store             0
320_other_services_in_store            0
304_additional_services_store          0
240_gender_interviewee                 0
indicate_the_type_of_store             0
name_of_the_store                      0
_latitude                              0
_longitude                             0
238_frequency_buying_store             0
81_number_online_purchases_month       0
288_number_app_purchases_month         0
289_number_whatsapp_purchases_month    0
83_willingness_ultrafast_delivery      0
84_willingness_sameday_delivery        0
241_age_of_the_interviewee             0
dtype: int64

In [18]:
#Convertir DataFrame a archivo .csv
Datos_limpios_consumer_mit_lift_lab.to_csv("Datos_limpios_consumer_mit_lift_lab.csv")

In [19]:
#Descargamos el archivo limpio
from google.colab import files 
files.download("Datos_limpios_consumer_mit_lift_lab.csv")

Microretailer_mit_lift_lab

In [20]:
filtro_cuantitativo_2=data2.iloc[ : , [5,6,13,14,16,21,22,29,31,33,42,58,59,60,90]]
filtro_cualitativo_2=data2.iloc[ : , [0,1,2,3,4,7,8,9,10,11,12,15,17,18,19,20,23,24,25,26,27,28,30,32,34,35,36,37,38,39,40,41,43,44,45,46,47,48,49,51,53,54,55,56,57,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,88,83,84,85,86,87,88,89,91,92,93,94,95,96,97,98,99,100,101,102,103,104]]

In [21]:
valores_nulos=filtro_cuantitativo_2.isnull().sum()
valores_nulos

_latitude                                              0
_longitude                                             0
97_number_of_customers_in_store                        0
268_number_fridges                                     3
104_how_many_shelves_does_the_micro_retailer_have      0
2_current_permanent_employees                         60
4_number_permanent_employees_last_year                76
103_number_own_fridges                               144
145_number_direct_competitors                         68
24_burnout                                           133
272_card_days_receive_money                          127
317_home_deliveries                                  154
62_frequency_only_services                           147
78_number_home_deliveries_week                       169
163_number_high_perishable_products                   93
dtype: int64

In [22]:
filtro_cuantitativo_2=filtro_cuantitativo_2.fillna(round(filtro_cuantitativo_2.mean(),1))

In [23]:
valores_nulos=filtro_cuantitativo_2.isnull().sum()
valores_nulos

_latitude                                            0
_longitude                                           0
97_number_of_customers_in_store                      0
268_number_fridges                                   0
104_how_many_shelves_does_the_micro_retailer_have    0
2_current_permanent_employees                        0
4_number_permanent_employees_last_year               0
103_number_own_fridges                               0
145_number_direct_competitors                        0
24_burnout                                           0
272_card_days_receive_money                          0
317_home_deliveries                                  0
62_frequency_only_services                           0
78_number_home_deliveries_week                       0
163_number_high_perishable_products                  0
dtype: int64

In [24]:
valores_nulos=filtro_cualitativo_2.isnull().sum()
valores_nulos

_record_id                                          0
_title                                              0
_server_updated_at                                  0
_updated_by                                         0
_geometry                                           0
                                                 ...
267_technology_investment_customer_preferences    101
234_willingness_participate_workshop               73
318_shopkeeper_name                               123
319_shopkeepers_last_name                         125
236_whatsapp                                      129
Length: 86, dtype: int64

In [25]:
filtro_cualitativo_2=filtro_cualitativo_2.fillna(method="bfill") 
filtro_cualitativo_2

,_record_id,_title,_server_updated_at,_updated_by,_geometry,228_store_name,229_store_picture,232_type_of_store,108_does_the_micro_retailer_has_a_barred_window_,99_does_the_micro_retailer_exhibits_products_outside_,...,260_technology_scalable,261_technology_organization,262_technology_serve_customers,263_technology_secure_sales,264_technology_budget,267_technology_investment_customer_preferences,234_willingness_participate_workshop,318_shopkeeper_name,319_shopkeepers_last_name,236_whatsapp
0,dff2998e-af74-4de6-8efd-488aca24e67b,"November 12, 2022",2022-11-12 22:15:10 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.233822273 19.0535362706),Eugene’s Compostura,1 Photo,Tailor,yes,no,...,En desacuerdo,De acuerdo,De acuerdo,Ni de acuerdo ni en desacuerdo,En desacuerdo,En desacuerdo,no,Fernanda,Escobedo,2.224524e+09
1,c596412f-4fc2-4983-acba-d9565859e42f,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2341421351 19.0535610353),Frutas y verduras Angy,1 Photo,Grocery store (aka. nanostore),no,yes,...,En desacuerdo,De acuerdo,De acuerdo,Ni de acuerdo ni en desacuerdo,En desacuerdo,En desacuerdo,no,Fernanda,Escobedo,2.224524e+09
2,5bb632b3-41b5-4fb6-a817-b564e8b45a48,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.232299887 19.058654656),Libélula,1 Photo,Grocery store (aka. nanostore),yes,no,...,En desacuerdo,De acuerdo,De acuerdo,Ni de acuerdo ni en desacuerdo,En desacuerdo,En desacuerdo,no,Fernanda,Escobedo,2.224524e+09
3,6774a0f6-bab4-4a58-bf94-95ad0b7cb438,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2331576513 19.0592929035),Quality fix,1 Photo,Grocery store (aka. nanostore),no,no,...,En desacuerdo,De acuerdo,De acuerdo,Ni de acuerdo ni en desacuerdo,En desacuerdo,En desacuerdo,no,Fernanda,Escobedo,2.224524e+09
4,6cc637fa-3d54-48c7-9499-6de13d0a26aa,"November 12, 2022",2022-11-12 22:15:08 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2338639604 19.0595846029),Artesanías Los Pinos,1 Photo,Grocery store (aka. nanostore),yes,no,...,En desacuerdo,De acuerdo,De acuerdo,Ni de acuerdo ni en desacuerdo,En desacuerdo,En desacuerdo,no,Fernanda,Escobedo,2.224524e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,2413f06e-15cc-4a6f-8e83-5224c6824b12,"November 3, 2022",2022-11-03 16:50:48 UTC,Emilio Garza,SRID=4326;POINT(-98.1940658722 19.0431145635),July Store,1 Photo,Grocery store (aka. nanostore),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,962bf5a6-1eff-4874-a627-9cd8e3ca27b4,"November 3, 2022",2022-11-03 16:28:15 UTC,Emilio Garza,SRID=4326;POINT(-98.1938023854 19.0427938182),Miscelánea rubí,1 Photo,Grocery store (aka. nanostore),no,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,9ff658db-4dc5-48b6-aa0b-5c6668bb6720,"November 3, 2022",2022-11-03 16:28:14 UTC,Emilio Garza,SRID=4326;POINT(-98.1934387078 19.0428094171),La fonda,1 Photo,Micro-restaurant (aka. fondita),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,e88aa9c1-dc8b-4180-99a1-2e0118ad905d,"November 3, 2022",2022-11-03 16:18:37 UTC,Francisco Adán,SRID=4326;POINT(-98.193818 19.042558),"Birria de Res ""Hermanos Negreros 2"" estilo Tij...",1 Photo,Micro-restaurant (aka. fondita),no,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,bf720ff0-3b7d-47ed-ba49-f5d4bfb7293c,"November 3, 2022",2022-11-03 16:15:13 UTC,Emilio Garza,SRID=4326;POINT(-98.1937349172 19.0428229892),Restaurante el alfeñique,1 Photo,Micro-restaurant (aka. fondita),no,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
valores_nulos=filtro_cualitativo_2.isnull().sum()
valores_nulos

_record_id                                        0
_title                                            0
_server_updated_at                                0
_updated_by                                       0
_geometry                                         0
                                                 ..
267_technology_investment_customer_preferences    5
234_willingness_participate_workshop              5
318_shopkeeper_name                               5
319_shopkeepers_last_name                         5
236_whatsapp                                      5
Length: 86, dtype: int64

In [27]:
y=filtro_cuantitativo_2

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _latitude                                            19.138774
_longitude                                          -98.075320
97_number_of_customers_in_store                       5.000000
268_number_fridges                                    5.000000
104_how_many_shelves_does_the_micro_retailer_have    16.000000
2_current_permanent_employees                         3.750000
4_number_permanent_employees_last_year                3.250000
103_number_own_fridges                                2.500000
145_number_direct_competitors                         6.750000
24_burnout                                            4.200000
272_card_days_receive_money                           1.000000
317_home_deliveries                                  13.600000
62_frequency_only_services                           10.500000
78_number_home_deliveries_week                        2.000000
163_number_high_perishable_products                  18.500000
dtype: float64
Limite inferior permitido _latitude                                            18.950047
_longitude                                          -98.355995
97_number_of_customers_in_store                      -3.000000
268_number_fridges                                   -3.000000
104_how_many_shelves_does_the_micro_retailer_have    -8.000000
2_current_permanent_employees                        -0.650000
4_number_permanent_employees_last_year               -0.350000
103_number_own_fridges                                2.500000
145_number_direct_competitors                        -0.850000
24_burnout                                            4.200000
272_card_days_receive_money                           1.000000
317_home_deliveries                                  13.600000
62_frequency_only_services                           10.500000
78_number_home_deliveries_week                        2.000000
163_number_high_perishable_products                  -7.900000
dtype: float64

In [28]:
outliers_iqr=filtro_cuantitativo_2[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr

,_latitude,_longitude,97_number_of_customers_in_store,268_number_fridges,104_how_many_shelves_does_the_micro_retailer_have,2_current_permanent_employees,4_number_permanent_employees_last_year,103_number_own_fridges,145_number_direct_competitors,24_burnout,272_card_days_receive_money,317_home_deliveries,62_frequency_only_services,78_number_home_deliveries_week,163_number_high_perishable_products
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0
2,NaN,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,60.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data3_iqr=filtro_cuantitativo_2[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

,_latitude,_longitude,97_number_of_customers_in_store,268_number_fridges,104_how_many_shelves_does_the_micro_retailer_have,2_current_permanent_employees,4_number_permanent_employees_last_year,103_number_own_fridges,145_number_direct_competitors,24_burnout,272_card_days_receive_money,317_home_deliveries,62_frequency_only_services,78_number_home_deliveries_week,163_number_high_perishable_products
0,19.053536,-98.233822,2.0,0.0,4.0,2.0,2.0,2.5,3.0,4.2,1.0,13.6,10.5,2.0,0.0
1,19.053561,-98.234142,0.0,4.0,8.0,1.0,1.0,2.5,4.0,4.2,1.0,13.6,10.5,2.0,NaN
2,19.058655,-98.232300,0.0,0.0,NaN,2.0,2.0,2.5,0.0,4.2,NaN,13.6,10.5,2.0,NaN
3,19.059293,-98.233158,0.0,0.0,2.0,1.0,1.0,2.5,4.0,4.2,NaN,13.6,10.5,2.0,0.0
4,19.059585,-98.233864,0.0,0.0,16.0,0.0,0.0,2.5,0.0,4.2,1.0,13.6,10.5,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,19.043115,-98.194066,1.0,0.0,5.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
167,19.042794,-98.193802,1.0,5.0,5.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
168,19.042809,-98.193439,3.0,1.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
169,19.042558,-98.193818,0.0,1.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
170,19.042823,-98.193735,1.0,3.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6

In [30]:
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

_latitude                                             0
_longitude                                            0
97_number_of_customers_in_store                       5
268_number_fridges                                   10
104_how_many_shelves_does_the_micro_retailer_have     9
2_current_permanent_employees                        15
4_number_permanent_employees_last_year               12
103_number_own_fridges                               27
145_number_direct_competitors                        15
24_burnout                                           38
272_card_days_receive_money                          14
317_home_deliveries                                  17
62_frequency_only_services                           24
78_number_home_deliveries_week                        2
163_number_high_perishable_products                  17
dtype: int64

In [31]:
data5_iqr=data3_iqr.copy()
data5_iqr=data5_iqr.fillna(round(data3_iqr.mean(),1))
data5_iqr

,_latitude,_longitude,97_number_of_customers_in_store,268_number_fridges,104_how_many_shelves_does_the_micro_retailer_have,2_current_permanent_employees,4_number_permanent_employees_last_year,103_number_own_fridges,145_number_direct_competitors,24_burnout,272_card_days_receive_money,317_home_deliveries,62_frequency_only_services,78_number_home_deliveries_week,163_number_high_perishable_products
0,19.053536,-98.233822,2.0,0.0,4.0,2.0,2.0,2.5,3.0,4.2,1.0,13.6,10.5,2.0,0.0
1,19.053561,-98.234142,0.0,4.0,8.0,1.0,1.0,2.5,4.0,4.2,1.0,13.6,10.5,2.0,6.1
2,19.058655,-98.232300,0.0,0.0,4.0,2.0,2.0,2.5,0.0,4.2,1.0,13.6,10.5,2.0,6.1
3,19.059293,-98.233158,0.0,0.0,2.0,1.0,1.0,2.5,4.0,4.2,1.0,13.6,10.5,2.0,0.0
4,19.059585,-98.233864,0.0,0.0,16.0,0.0,0.0,2.5,0.0,4.2,1.0,13.6,10.5,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,19.043115,-98.194066,1.0,0.0,5.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
167,19.042794,-98.193802,1.0,5.0,5.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
168,19.042809,-98.193439,3.0,1.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
169,19.042558,-98.193818,0.0,1.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
170,19.042823,-98.193735,1.0,3.0,1.0,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6

In [32]:
Datos_limpios_microretailer_mit_lift_lab = pd.concat([filtro_cualitativo_2, data5_iqr], axis=1)
Datos_limpios_microretailer_mit_lift_lab

,_record_id,_title,_server_updated_at,_updated_by,_geometry,228_store_name,229_store_picture,232_type_of_store,108_does_the_micro_retailer_has_a_barred_window_,99_does_the_micro_retailer_exhibits_products_outside_,...,2_current_permanent_employees,4_number_permanent_employees_last_year,103_number_own_fridges,145_number_direct_competitors,24_burnout,272_card_days_receive_money,317_home_deliveries,62_frequency_only_services,78_number_home_deliveries_week,163_number_high_perishable_products
0,dff2998e-af74-4de6-8efd-488aca24e67b,"November 12, 2022",2022-11-12 22:15:10 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.233822273 19.0535362706),Eugene’s Compostura,1 Photo,Tailor,yes,no,...,2.0,2.0,2.5,3.0,4.2,1.0,13.6,10.5,2.0,0.0
1,c596412f-4fc2-4983-acba-d9565859e42f,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2341421351 19.0535610353),Frutas y verduras Angy,1 Photo,Grocery store (aka. nanostore),no,yes,...,1.0,1.0,2.5,4.0,4.2,1.0,13.6,10.5,2.0,6.1
2,5bb632b3-41b5-4fb6-a817-b564e8b45a48,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.232299887 19.058654656),Libélula,1 Photo,Grocery store (aka. nanostore),yes,no,...,2.0,2.0,2.5,0.0,4.2,1.0,13.6,10.5,2.0,6.1
3,6774a0f6-bab4-4a58-bf94-95ad0b7cb438,"November 12, 2022",2022-11-12 22:15:09 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2331576513 19.0592929035),Quality fix,1 Photo,Grocery store (aka. nanostore),no,no,...,1.0,1.0,2.5,4.0,4.2,1.0,13.6,10.5,2.0,0.0
4,6cc637fa-3d54-48c7-9499-6de13d0a26aa,"November 12, 2022",2022-11-12 22:15:08 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2338639604 19.0595846029),Artesanías Los Pinos,1 Photo,Grocery store (aka. nanostore),yes,no,...,0.0,0.0,2.5,0.0,4.2,1.0,13.6,10.5,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,2413f06e-15cc-4a6f-8e83-5224c6824b12,"November 3, 2022",2022-11-03 16:50:48 UTC,Emilio Garza,SRID=4326;POINT(-98.1940658722 19.0431145635),July Store,1 Photo,Grocery store (aka. nanostore),yes,no,...,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
167,962bf5a6-1eff-4874-a627-9cd8e3ca27b4,"November 3, 2022",2022-11-03 16:28:15 UTC,Emilio Garza,SRID=4326;POINT(-98.1938023854 19.0427938182),Miscelánea rubí,1 Photo,Grocery store (aka. nanostore),no,no,...,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
168,9ff658db-4dc5-48b6-aa0b-5c6668bb6720,"November 3, 2022",2022-11-03 16:28:14 UTC,Emilio Garza,SRID=4326;POINT(-98.1934387078 19.0428094171),La fonda,1 Photo,Micro-restaurant (aka. fondita),yes,no,...,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
169,e88aa9c1-dc8b-4180-99a1-2e0118ad905d,"November 3, 2022",2022-11-03 16:18:37 UTC,Francisco Adán,SRID=4326;POINT(-98.193818 19.042558),"Birria de Res ""Hermanos Negreros 2"" estilo Tij...",1 Photo,Micro-restaurant (aka. fondita),no,no,...,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6
170,bf720ff0-3b7d-47ed-ba49-f5d4bfb7293c,"November 3, 2022",2022-11-03 16:15:13 UTC,Emilio Garza,SRID=4326;POINT(-98.1937349172 19.0428229892),Restaurante el alfeñique,1 Photo,Micro-restaurant (aka. fondita),no,no,...,2.1,1.9,2.5,3.8,4.2,1.0,13.6,10.5,2.0,8.6

In [33]:
Datos_limpios_microretailer_mit_lift_lab.to_csv("Datos_limpios_microretailer_mit_lift_lab.csv")

In [34]:
from google.colab import files 
files.download("Datos_limpios_microretailer_mit_lift_lab.csv")

Lastmile_delivery_operations_mit_lift_lab

In [35]:
filtro_cuantitativo_3=data3.iloc[ : , [5,6,12,21,22,28]]
filtro_cualitativo_3=data3.iloc[ : , [0,1,2,3,4,7,8,9,10,11,13,14,15,16,17,18,19,20,23,24,25,26,27]]

In [36]:
valores_nulos=filtro_cuantitativo_3.isnull().sum()
valores_nulos

_latitude                                          0
_longitude                                         0
number_of_operators                                0
number_of_available_trolleys                       0
serving_customer                                 147
maximum_number_of_vehicles_in_the_traffic_jam    180
dtype: int64

In [37]:
#Sustituir valores nulos por media.
filtro_cuantitativo_3["serving_customer"]=filtro_cuantitativo_3["serving_customer"].fillna(round(filtro_cuantitativo_3["serving_customer"].mean(),1))
#Sustituir valores nulos por un valor numérico.
filtro_cuantitativo_3["maximum_number_of_vehicles_in_the_traffic_jam"]= filtro_cuantitativo_3["maximum_number_of_vehicles_in_the_traffic_jam"].fillna(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [38]:
y=filtro_cuantitativo_3

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr=percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _latitude                                        19.123517
_longitude                                      -98.098434
number_of_operators                               3.500000
number_of_available_trolleys                      2.500000
serving_customer                                  1.000000
maximum_number_of_vehicles_in_the_traffic_jam     0.000000
dtype: float64
Limite inferior permitido _latitude                                        18.961271
_longitude                                      -98.366619
number_of_operators                              -0.500000
number_of_available_trolleys                     -1.500000
serving_customer                                  1.000000
maximum_number_of_vehicles_in_the_traffic_jam     0.000000
dtype: float64

In [39]:
outliers_iqr=filtro_cuantitativo_3[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr

,_latitude,_longitude,number_of_operators,number_of_available_trolleys,serving_customer,maximum_number_of_vehicles_in_the_traffic_jam
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
177,NaN,NaN,NaN,NaN,NaN,NaN
178,NaN,NaN,NaN,NaN,NaN,NaN
179,NaN,NaN,NaN,NaN,NaN,NaN
180,NaN,NaN,NaN,NaN,NaN,NaN
181,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
data3_iqr=filtro_cuantitativo_3[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

,_latitude,_longitude,number_of_operators,number_of_available_trolleys,serving_customer,maximum_number_of_vehicles_in_the_traffic_jam
0,19.056893,-98.233489,1.0,1.0,1.0,0.0
1,19.056849,-98.233484,2.0,1.0,1.0,0.0
2,19.059677,-98.233916,1.0,0.0,1.0,0.0
3,19.062695,-98.228567,1.0,2.0,1.0,0.0
4,19.062724,-98.231397,2.0,2.0,1.0,0.0
...,...,...,...,...,...,...
177,19.043612,-98.194933,1.0,0.0,1.0,0.0
178,19.043607,-98.194856,1.0,0.0,1.0,0.0
179,19.043336,-98.194503,1.0,1.0,1.0,0.0
180,19.043576,-98.194873,2.0,0.0,1.0,0.0
181,19.043590,-98.194901,2.0,1.0,1.0,0.0

In [41]:
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

_latitude                                         0
_longitude                                        0
number_of_operators                              10
number_of_available_trolleys                      2
serving_customer                                  0
maximum_number_of_vehicles_in_the_traffic_jam     2
dtype: int64

In [42]:
data5_iqr=data3_iqr.copy()
data5_iqr=data5_iqr.fillna(round(data3_iqr.mean(),1))
data5_iqr

,_latitude,_longitude,number_of_operators,number_of_available_trolleys,serving_customer,maximum_number_of_vehicles_in_the_traffic_jam
0,19.056893,-98.233489,1.0,1.0,1.0,0.0
1,19.056849,-98.233484,2.0,1.0,1.0,0.0
2,19.059677,-98.233916,1.0,0.0,1.0,0.0
3,19.062695,-98.228567,1.0,2.0,1.0,0.0
4,19.062724,-98.231397,2.0,2.0,1.0,0.0
...,...,...,...,...,...,...
177,19.043612,-98.194933,1.0,0.0,1.0,0.0
178,19.043607,-98.194856,1.0,0.0,1.0,0.0
179,19.043336,-98.194503,1.0,1.0,1.0,0.0
180,19.043576,-98.194873,2.0,0.0,1.0,0.0
181,19.043590,-98.194901,2.0,1.0,1.0,0.0

In [43]:
valores_nulos=filtro_cualitativo_3.isnull().sum()
valores_nulos

_record_id                                 0
_title                                     6
_server_updated_at                         0
_updated_by                                0
_geometry                                  0
arrival_of_the_freight_vehicle             0
plates                                     1
company_if_visible                        73
visit_purpose                              0
type_of_vehicle                            0
refrigerated_truck                         0
type_of_cargo                              0
picture_of_the_parked_freight_vehicle      0
departure_of_the_freight_vehicle           0
where_was_the_vehicle_parked               0
while_parked_was_the_engine_running        0
used_traffic_cone                          0
vehicles_unloading_door                    0
garage_blocking                            0
accident                                   0
describe_the_accident                    182
noise                                      0
traffic_congestion                         0
dtype: int64

In [44]:
filtro_cualitativo_3=filtro_cualitativo_3.fillna(method="bfill") 
filtro_cualitativo_3

,_record_id,_title,_server_updated_at,_updated_by,_geometry,arrival_of_the_freight_vehicle,plates,company_if_visible,visit_purpose,type_of_vehicle,...,departure_of_the_freight_vehicle,where_was_the_vehicle_parked,while_parked_was_the_engine_running,used_traffic_cone,vehicles_unloading_door,garage_blocking,accident,describe_the_accident,noise,traffic_congestion
0,4408a234-9585-46fe-9b16-96c0faaf6db8,73 Calle Almolonga\nPuebla de Zaragoza PUE 721...,2022-11-12 22:15:04 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2334894708 19.0568933787),14:00,KB-7050-A,Ricolino,Delivery,Light truck or Van,...,14:10,Street - next to the curbside,no,no,Side,yes,no,NaN,no,no
1,673cd0e3-7290-4c4d-a57f-096d16b78141,72 Calle Almolonga\nPuebla de Zaragoza PUE 721...,2022-11-12 20:41:39 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.233483903 19.0568494313),13:50,XC8687A,Marinela,Delivery,Heavy duty truck,...,14:10,Street - next to the curbside,no,no,Rear,no,no,NaN,no,no
2,04e64464-3fbd-4ce1-99d8-5364e1567e8c,4510 Vía Volkswagen\nHeroica Puebla de Zaragoz...,2022-11-12 18:02:57 UTC,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2339161 19.0596775),11:47,SM 20745,La fete,Delivery,Pick-up,...,12:13,Street - next to the curbside,no,no,Side,no,no,NaN,no,no
3,d0a6568d-cf8f-48fd-ad3d-007e79f4ae6b,4501A Avenida 2 Poniente\nHeroica Puebla de Za...,2022-11-12 17:55:44 UTC,Luis Gerardo Ramírez Lastra,SRID=4326;POINT(-98.2285674 19.0626948),11:45,SP35169,Barcel,Delivery,Light truck or Van,...,11:53,Street - next to the curbside,yes,no,Rear,yes,no,NaN,no,no
4,eff15823-b1f2-4e82-afb2-2195635d1406,4717 Avenida Reforma\nHeroica Puebla de Zarago...,2022-11-12 17:55:44 UTC,Luis Gerardo Ramírez Lastra,SRID=4326;POINT(-98.231397 19.0627239),11:41,SN89460,Agua inmaculada,Delivery,Light truck or Van,...,12:00,Dedicated unloading area (Bay),no,no,Rear,no,no,NaN,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,f964004e-67a0-4b75-b2b0-ce04b9f0b344,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:56 UTC,José Oropeza,SRID=4326;POINT(-98.194933077 19.043612116),10:36,HL-3785-F,Infra,Delivery,Light truck or Van,...,11:00,Street - next to the curbside,no,no,Rear,no,no,NaN,no,no
178,5656a189-19f5-45a7-b53b-1a3db0de6571,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:56 UTC,José Oropeza,SRID=4326;POINT(-98.1948560508 19.0436070826),10:33,SP-29-798,Infra,Delivery,Light truck or Van,...,10:50,Street - next to the curbside,no,no,Side,no,no,NaN,no,no
179,bcbd462b-4c63-490b-bfec-0ef6657ead73,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:44 UTC,Emilio Garza,SRID=4326;POINT(-98.1945033093 19.043335537),11:19,05-AP-6G,Infra,Delivery,Light truck or Van,...,11:21,Street - next to the curbside,no,no,Rear,no,no,NaN,no,no
180,cd9ba76d-d899-4d87-9512-486aedb1b149,402E Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:14:09 UTC,Emilio Garza,SRID=4326;POINT(-98.1948728731 19.0435760418),11:03,LE-88-707,Alpura,Delivery,Pick-up,...,11:04,Street - next to the curbside,no,no,Rear,no,no,NaN,no,no
181,657541f6-7871-4165-80b2-bef59db83e18,402 Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:14:09 UTC,Emilio Garza,SRID=4326;POINT(-98.1949010531 19.043589516),11:00,HL-3785-F,Bimbo,Delivery,Pick-up,...,11:08,Street - next to the curbside,yes,no,Rear,no,no,NaN,no,no

In [45]:
valores_nulos=filtro_cualitativo.isnull().sum()
valores_nulos

_record_id                            0
_title                                0
_server_updated_at                    0
_updated_by                           0
_geometry                             0
282_payment_method_that_purchase      0
283_fulfill_needs                     0
300_did_not_find                      0
237_distance_household_interviewee    0
299_means_transportation_consumer     0
284_additional_products_store         0
301_electricity_bill                  0
305_electricity_bill_store            0
302_water_bill                        0
306_water_bill_store                  0
303_gas_bill                          0
307_gas_bill_store                    0
286_topups                            0
308_topups_in_store                   0
287_wire_transfers                    0
309_wiretransfers_in_store            0
320_other_services_in_store           0
304_additional_services_store         0
240_gender_interviewee                0
indicate_the_type_of_store            0
name_of_the_store                     0
dtype: int64

In [46]:
Datos_limpios_lastmile_delivery_operations_mit_lift_lab = pd.concat([filtro_cualitativo_3, data5_iqr], axis=1)
Datos_limpios_lastmile_delivery_operations_mit_lift_lab

,_record_id,_title,_server_updated_at,_updated_by,_geometry,arrival_of_the_freight_vehicle,plates,company_if_visible,visit_purpose,type_of_vehicle,...,accident,describe_the_accident,noise,traffic_congestion,_latitude,_longitude,number_of_operators,number_of_available_trolleys,serving_customer,maximum_number_of_vehicles_in_the_traffic_jam
0,4408a234-9585-46fe-9b16-96c0faaf6db8,73 Calle Almolonga\nPuebla de Zaragoza PUE 721...,2022-11-12 22:15:04 UTC,Salomon Abdala Perez,SRID=4326;POINT(-98.2334894708 19.0568933787),14:00,KB-7050-A,Ricolino,Delivery,Light truck or Van,...,no,NaN,no,no,19.056893,-98.233489,1.0,1.0,1.0,0.0
1,673cd0e3-7290-4c4d-a57f-096d16b78141,72 Calle Almolonga\nPuebla de Zaragoza PUE 721...,2022-11-12 20:41:39 UTC,Jorge Alberto Ostorga Flores,SRID=4326;POINT(-98.233483903 19.0568494313),13:50,XC8687A,Marinela,Delivery,Heavy duty truck,...,no,NaN,no,no,19.056849,-98.233484,2.0,1.0,1.0,0.0
2,04e64464-3fbd-4ce1-99d8-5364e1567e8c,4510 Vía Volkswagen\nHeroica Puebla de Zaragoz...,2022-11-12 18:02:57 UTC,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2339161 19.0596775),11:47,SM 20745,La fete,Delivery,Pick-up,...,no,NaN,no,no,19.059677,-98.233916,1.0,0.0,1.0,0.0
3,d0a6568d-cf8f-48fd-ad3d-007e79f4ae6b,4501A Avenida 2 Poniente\nHeroica Puebla de Za...,2022-11-12 17:55:44 UTC,Luis Gerardo Ramírez Lastra,SRID=4326;POINT(-98.2285674 19.0626948),11:45,SP35169,Barcel,Delivery,Light truck or Van,...,no,NaN,no,no,19.062695,-98.228567,1.0,2.0,1.0,0.0
4,eff15823-b1f2-4e82-afb2-2195635d1406,4717 Avenida Reforma\nHeroica Puebla de Zarago...,2022-11-12 17:55:44 UTC,Luis Gerardo Ramírez Lastra,SRID=4326;POINT(-98.231397 19.0627239),11:41,SN89460,Agua inmaculada,Delivery,Light truck or Van,...,no,NaN,no,no,19.062724,-98.231397,2.0,2.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,f964004e-67a0-4b75-b2b0-ce04b9f0b344,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:56 UTC,José Oropeza,SRID=4326;POINT(-98.194933077 19.043612116),10:36,HL-3785-F,Infra,Delivery,Light truck or Van,...,no,NaN,no,no,19.043612,-98.194933,1.0,0.0,1.0,0.0
178,5656a189-19f5-45a7-b53b-1a3db0de6571,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:56 UTC,José Oropeza,SRID=4326;POINT(-98.1948560508 19.0436070826),10:33,SP-29-798,Infra,Delivery,Light truck or Van,...,no,NaN,no,no,19.043607,-98.194856,1.0,0.0,1.0,0.0
179,bcbd462b-4c63-490b-bfec-0ef6657ead73,406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:54:44 UTC,Emilio Garza,SRID=4326;POINT(-98.1945033093 19.043335537),11:19,05-AP-6G,Infra,Delivery,Light truck or Van,...,no,NaN,no,no,19.043336,-98.194503,1.0,1.0,1.0,0.0
180,cd9ba76d-d899-4d87-9512-486aedb1b149,402E Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:14:09 UTC,Emilio Garza,SRID=4326;POINT(-98.1948728731 19.0435760418),11:03,LE-88-707,Alpura,Delivery,Pick-up,...,no,NaN,no,no,19.043576,-98.194873,2.0,0.0,1.0,0.0
181,657541f6-7871-4165-80b2-bef59db83e18,402 Avenida 2 Oriente\nPuebla PUE 72000\nMX,2022-11-03 17:14:09 UTC,Emilio Garza,SRID=4326;POINT(-98.1949010531 19.043589516),11:00,HL-3785-F,Bimbo,Delivery,Pick-up,...,no,NaN,no,no,19.043590,-98.194901,2.0,1.0,1.0,0.0

In [47]:
valores_nulos=Datos_limpios_lastmile_delivery_operations_mit_lift_lab.isnull().sum()
valores_nulos

_record_id                                         0
_title                                             0
_server_updated_at                                 0
_updated_by                                        0
_geometry                                          0
arrival_of_the_freight_vehicle                     0
plates                                             0
company_if_visible                                 0
visit_purpose                                      0
type_of_vehicle                                    0
refrigerated_truck                                 0
type_of_cargo                                      0
picture_of_the_parked_freight_vehicle              0
departure_of_the_freight_vehicle                   0
where_was_the_vehicle_parked                       0
while_parked_was_the_engine_running                0
used_traffic_cone                                  0
vehicles_unloading_door                            0
garage_blocking                                    0
accident                                           0
describe_the_accident                            182
noise                                              0
traffic_congestion                                 0
_latitude                                          0
_longitude                                         0
number_of_operators                                0
number_of_available_trolleys                       0
serving_customer                                   0
maximum_number_of_vehicles_in_the_traffic_jam      0
dtype: int64

In [48]:
Datos_limpios_lastmile_delivery_operations_mit_lift_lab["describe_the_accident"] =Datos_limpios_lastmile_delivery_operations_mit_lift_lab["describe_the_accident"].fillna("NA")

In [49]:
valores_nulos=Datos_limpios_lastmile_delivery_operations_mit_lift_lab.isnull().sum()
valores_nulos

_record_id                                       0
_title                                           0
_server_updated_at                               0
_updated_by                                      0
_geometry                                        0
arrival_of_the_freight_vehicle                   0
plates                                           0
company_if_visible                               0
visit_purpose                                    0
type_of_vehicle                                  0
refrigerated_truck                               0
type_of_cargo                                    0
picture_of_the_parked_freight_vehicle            0
departure_of_the_freight_vehicle                 0
where_was_the_vehicle_parked                     0
while_parked_was_the_engine_running              0
used_traffic_cone                                0
vehicles_unloading_door                          0
garage_blocking                                  0
accident                                         0
describe_the_accident                            0
noise                                            0
traffic_congestion                               0
_latitude                                        0
_longitude                                       0
number_of_operators                              0
number_of_available_trolleys                     0
serving_customer                                 0
maximum_number_of_vehicles_in_the_traffic_jam    0
dtype: int64

In [50]:
Datos_limpios_lastmile_delivery_operations_mit_lift_lab.to_csv("Datos_limpios_lastmile_delivery_operations_mit_lift_lab.csv")

In [51]:
from google.colab import files 
files.download("Datos_limpios_lastmile_delivery_operations_mit_lift_lab.csv")

Lastmile_delivery_operations_mit_lift_lab_serving_customer

In [52]:
filtro_cuantitativo_4=data4.iloc[ : , [4,9,11,12,14,15,16,19,20,24]]
filtro_cualitativo_4=data4.iloc[ : , [0,1,2,3,5,6,7,8,10,13,17,18,21,22,23,25,26]]

In [53]:
valores_nulos=filtro_cuantitativo_4.isnull().sum()
valores_nulos

_version                           0
_index                             0
_latitude                          0
_longitude                         0
_created_duration                  0
_updated_duration                  0
_edited_duration                   0
number_of_customers_in_store       0
number_of_suppliers_in_store       0
number_of_cases_boxes_delivered    0
dtype: int64

In [54]:
valores_nulos=filtro_cualitativo_4.isnull().sum()
valores_nulos

_child_record_id                           0
_record_id                                 0
_parent_id                                 0
_title                                     0
_created_at                                0
_updated_at                                0
_created_by                                0
_updated_by                                0
_geometry                                  0
_changeset_id                              0
name_of_the_store                          0
entering_the_store                         0
picture_cargo_being_delivered             10
picture_cargo_being_delivered_captions    33
picture_cargo_being_delivered_urls        10
trolley_in_use                             0
leaving_the_store                          0
dtype: int64

In [55]:
#Sustituimos valores nulos por una valor "String".
filtro_cualitativo_4["picture_cargo_being_delivered"]=filtro_cualitativo_4["picture_cargo_being_delivered"].fillna("Sin foto")
filtro_cualitativo_4["picture_cargo_being_delivered_captions"]=filtro_cualitativo_4["picture_cargo_being_delivered_captions"].fillna("Sin foto")
filtro_cualitativo_4["picture_cargo_being_delivered_urls"]=filtro_cualitativo_4["picture_cargo_being_delivered_urls"].fillna("Sin foto")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [56]:
valores_nulos=filtro_cualitativo_4.isnull().sum()
valores_nulos

_child_record_id                          0
_record_id                                0
_parent_id                                0
_title                                    0
_created_at                               0
_updated_at                               0
_created_by                               0
_updated_by                               0
_geometry                                 0
_changeset_id                             0
name_of_the_store                         0
entering_the_store                        0
picture_cargo_being_delivered             0
picture_cargo_being_delivered_captions    0
picture_cargo_being_delivered_urls        0
trolley_in_use                            0
leaving_the_store                         0
dtype: int64

In [57]:
y=filtro_cuantitativo_4

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _version                             1.000000
_index                               0.000000
_latitude                           19.118961
_longitude                         -98.181767
_created_duration                    0.000000
_updated_duration                  177.250000
_edited_duration                   172.000000
number_of_customers_in_store         5.000000
number_of_suppliers_in_store         3.500000
number_of_cases_boxes_delivered     12.000000
dtype: float64
Limite inferior permitido _version                            1.000000
_index                              0.000000
_latitude                          18.935810
_longitude                        -98.319111
_created_duration                   0.000000
_updated_duration                 -40.750000
_edited_duration                  -32.000000
number_of_customers_in_store       -3.000000
number_of_suppliers_in_store       -0.500000
number_of_cases_boxes_delivered    -4.000000
dtype: float64

In [58]:
outliers_iqr=filtro_cuantitativo_4[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr

,_version,_index,_latitude,_longitude,_created_duration,_updated_duration,_edited_duration,number_of_customers_in_store,number_of_suppliers_in_store,number_of_cases_boxes_delivered
0,NaN,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,15.0
1,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,35.0
2,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,76.0,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,53.0,NaN,NaN,7.0,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,624.0,624.0,624.0,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,309.0,309.0,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,382.0,382.0,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,336.0,336.0,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,25.609546,-100.274162,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
data3_iqr=filtro_cuantitativo_4[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

,_version,_index,_latitude,_longitude,_created_duration,_updated_duration,_edited_duration,number_of_customers_in_store,number_of_suppliers_in_store,number_of_cases_boxes_delivered
0,1,0,19.059667,-98.233864,NaN,3.0,64.0,1.0,1.0,NaN
1,1,0,19.053049,-98.229422,NaN,80.0,80.0,0.0,2.0,NaN
2,1,0,19.051740,-98.232677,NaN,61.0,86.0,0.0,1.0,12.0
3,1,0,19.052990,-98.233991,NaN,7.0,48.0,0.0,1.0,3.0
4,1,0,19.055389,-98.230130,NaN,76.0,76.0,0.0,1.0,1.0
5,1,0,19.053104,-98.227161,NaN,53.0,53.0,NaN,1.0,3.0
6,1,0,19.045903,-98.203487,0.0,8.0,8.0,1.0,1.0,3.0
7,1,0,19.023488,-98.203281,0.0,4.0,4.0,2.0,1.0,3.0
8,1,0,19.046459,-98.193698,0.0,116.0,116.0,2.0,1.0,2.0
9,1,0,19.065868,-98.310562,NaN,NaN,NaN,3.0,2.0,11.0
10,1,0,19.064508,-98.311303,NaN,167.0,167.0,2.0,2.0,12.0
11,1,0,19.047385,-98.204255,0.0,130.0,130.0,NaN,1.0,5.0
12,1,0,19.048819,-98.200050,0.0,11.0,11.0,0.0,1.0,NaN
13,1,0,18.999429,-98.274060,0.0,78.0,78.0,1.0,3.0,8.0
14,1,0,18.999426,-98.274079,0.0,46.0,46.0,2.0,1.0,2.0
15,1,0,19.006088,-98.265674,0.0,50.0,50.0,2.0,NaN,10.0
16,1,0,19.006137,-98.265682,0.0,56.0,56.0,0.0,2.0,6.0
17,1,0,19.006115,-98.265670,0.0,41.0,41.0,0.0,1.0,2.0
18,1,0,19.004101,-98.266502,0.0,41.0,41.0,3.0,1.0,4.0
19,1,0,19.004110,-98.266491,0.0,81.0,81.0,2.0,1.0,2.0
20,1,0,19.004503,-98.266188,0.0,76.0,76.0,4.0,3.0,6.0
21,1,0,19.004481,-98.266204,0.0,40.0,40.0,4.0,2.0,5.0
22,1,0,18.999598,-98.274838,0.0,68.0,68.0,0.0,1.0,2.0
23,1,0,19.001842,-98.271896,0.0,60.0,60.0,0.0,2.0,5.0
24,1,0,19.001730,-98.272087,0.0,43.0,43.0,2.0,1.0,2.0
25,1,0,19.005120,-98.266486,0.0,94.0,94.0,1.0,2.0,3.0
26,1,0,19.005652,-98.267596,0.0,57.0,57.0,0.0,2.0,4.0
27,1,0,19.005692,-98.267617,0.0,97.0,97.0,0.0,1.0,4.0
28,1,0,19.004079,-98.266771,0.0,2.0,2.0,1.0,0.0,2.0
29,1,0,19.026688,-98.249335,0.0,NaN,NaN,0.0,1.0,2.0
30,1,0,19.025176,-98.249031,0.0,NaN,NaN,3.0,1.0,4.0
31,1,0,19.030839,-98.249791,0.0,1.0,1.0,1.0,2.0,5.0
32,1,0,19.030743,-98.249907,0.0,NaN,NaN,1.0,2.0,1.0
33,1,0,19.025156,-98.249055,0.0,168.0,168.0,4.0,1.0,2.0
34,1,0,NaN,NaN,0.0,62.0,62.0,0.0,1.0,1.0

In [60]:
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

_version                           0
_index                             0
_latitude                          1
_longitude                         1
_created_duration                  8
_updated_duration                  4
_edited_duration                   4
number_of_customers_in_store       2
number_of_suppliers_in_store       1
number_of_cases_boxes_delivered    3
dtype: int64

In [61]:
data5_iqr=data3_iqr.copy()
data5_iqr=data5_iqr.fillna(round(data3_iqr.mean(),1))
data5_iqr

,_version,_index,_latitude,_longitude,_created_duration,_updated_duration,_edited_duration,number_of_customers_in_store,number_of_suppliers_in_store,number_of_cases_boxes_delivered
0,1,0,19.059667,-98.233864,0.0,3.0,64.0,1.0,1.0,4.3
1,1,0,19.053049,-98.229422,0.0,80.0,80.0,0.0,2.0,4.3
2,1,0,19.051740,-98.232677,0.0,61.0,86.0,0.0,1.0,12.0
3,1,0,19.052990,-98.233991,0.0,7.0,48.0,0.0,1.0,3.0
4,1,0,19.055389,-98.230130,0.0,76.0,76.0,0.0,1.0,1.0
5,1,0,19.053104,-98.227161,0.0,53.0,53.0,1.3,1.0,3.0
6,1,0,19.045903,-98.203487,0.0,8.0,8.0,1.0,1.0,3.0
7,1,0,19.023488,-98.203281,0.0,4.0,4.0,2.0,1.0,3.0
8,1,0,19.046459,-98.193698,0.0,116.0,116.0,2.0,1.0,2.0
9,1,0,19.065868,-98.310562,0.0,60.5,64.6,3.0,2.0,11.0
10,1,0,19.064508,-98.311303,0.0,167.0,167.0,2.0,2.0,12.0
11,1,0,19.047385,-98.204255,0.0,130.0,130.0,1.3,1.0,5.0
12,1,0,19.048819,-98.200050,0.0,11.0,11.0,0.0,1.0,4.3
13,1,0,18.999429,-98.274060,0.0,78.0,78.0,1.0,3.0,8.0
14,1,0,18.999426,-98.274079,0.0,46.0,46.0,2.0,1.0,2.0
15,1,0,19.006088,-98.265674,0.0,50.0,50.0,2.0,1.4,10.0
16,1,0,19.006137,-98.265682,0.0,56.0,56.0,0.0,2.0,6.0
17,1,0,19.006115,-98.265670,0.0,41.0,41.0,0.0,1.0,2.0
18,1,0,19.004101,-98.266502,0.0,41.0,41.0,3.0,1.0,4.0
19,1,0,19.004110,-98.266491,0.0,81.0,81.0,2.0,1.0,2.0
20,1,0,19.004503,-98.266188,0.0,76.0,76.0,4.0,3.0,6.0
21,1,0,19.004481,-98.266204,0.0,40.0,40.0,4.0,2.0,5.0
22,1,0,18.999598,-98.274838,0.0,68.0,68.0,0.0,1.0,2.0
23,1,0,19.001842,-98.271896,0.0,60.0,60.0,0.0,2.0,5.0
24,1,0,19.001730,-98.272087,0.0,43.0,43.0,2.0,1.0,2.0
25,1,0,19.005120,-98.266486,0.0,94.0,94.0,1.0,2.0,3.0
26,1,0,19.005652,-98.267596,0.0,57.0,57.0,0.0,2.0,4.0
27,1,0,19.005692,-98.267617,0.0,97.0,97.0,0.0,1.0,4.0
28,1,0,19.004079,-98.266771,0.0,2.0,2.0,1.0,0.0,2.0
29,1,0,19.026688,-98.249335,0.0,60.5,64.6,0.0,1.0,2.0
30,1,0,19.025176,-98.249031,0.0,60.5,64.6,3.0,1.0,4.0
31,1,0,19.030839,-98.249791,0.0,1.0,1.0,1.0,2.0,5.0
32,1,0,19.030743,-98.249907,0.0,60.5,64.6,1.0,2.0,1.0
33,1,0,19.025156,-98.249055,0.0,168.0,168.0,4.0,1.0,2.0
34,1,0,19.000000,-98.300000,0.0,62.0,62.0,0.0,1.0,1.0

In [62]:
Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer = pd.concat([filtro_cualitativo_4, data5_iqr], axis=1)
Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer

,_child_record_id,_record_id,_parent_id,_title,_created_at,_updated_at,_created_by,_updated_by,_geometry,_changeset_id,...,_version,_index,_latitude,_longitude,_created_duration,_updated_duration,_edited_duration,number_of_customers_in_store,number_of_suppliers_in_store,number_of_cases_boxes_delivered
0,12645bc3-33b6-4cc0-9c8e-9d8e6f35aa01,04e64464-3fbd-4ce1-99d8-5364e1567e8c,04e64464-3fbd-4ce1-99d8-5364e1567e8c,La fete,2022-11-12 18:00:54 UTC,2022-11-12 18:02:03 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2338643 19.0596667),1f557f2f-5ba3-4de9-aa53-86fc8bc120eb,...,1,0,19.059667,-98.233864,0.0,3.0,64.0,1.0,1.0,4.3
1,be0fc402-769c-41f8-90f1-1b0c9f151e7a,cda7b134-7827-4830-9337-53f46be4f8b4,cda7b134-7827-4830-9337-53f46be4f8b4,Casa Flores,2022-11-12 16:54:27 UTC,2022-11-12 16:55:48 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2294218 19.0530488),6cbfadf7-671c-4a48-8ac4-0ad1e94d426a,...,1,0,19.053049,-98.229422,0.0,80.0,80.0,0.0,2.0,4.3
2,634bbd94-8159-4733-973a-36ab89fb95d4,cbaab095-ad31-4145-804b-ddc218681802,cbaab095-ad31-4145-804b-ddc218681802,Super deux,2022-11-12 16:43:26 UTC,2022-11-12 16:45:00 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.232677 19.0517402),e4868227-703c-4c41-b9fe-31fad435c1f9,...,1,0,19.051740,-98.232677,0.0,61.0,86.0,0.0,1.0,12.0
3,cf8e05ea-0af9-4a66-9d8b-27c0cf572236,68b5ecad-36b0-4172-b2b3-43aebd0485ec,68b5ecad-36b0-4172-b2b3-43aebd0485ec,Dansk,2022-11-12 16:37:55 UTC,2022-11-12 16:38:54 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2339909 19.0529905),644c5a56-bd04-4959-afc3-017fbb7112e6,...,1,0,19.052990,-98.233991,0.0,7.0,48.0,0.0,1.0,3.0
4,a1ff05ef-fe15-472e-ad6d-537c951afce4,3b19bb47-17f0-4d33-aa27-cf6890bacfe5,3b19bb47-17f0-4d33-aa27-cf6890bacfe5,Ink Factory,2022-11-12 16:19:57 UTC,2022-11-12 16:21:14 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2301302 19.0553894),de88df96-b59b-4aca-bb27-5817dd9ddda0,...,1,0,19.055389,-98.230130,0.0,76.0,76.0,0.0,1.0,1.0
5,9e96f584-f5b2-4e7d-a754-a34fc89d5139,2b8a179a-521c-4ee3-a5ef-241fd1972b01,2b8a179a-521c-4ee3-a5ef-241fd1972b01,Breaking Bread Coffee,2022-11-12 15:59:13 UTC,2022-11-12 16:00:07 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,SRID=4326;POINT(-98.2271606 19.0531043),3bb014cc-8973-49bb-9942-924bc871ddb9,...,1,0,19.053104,-98.227161,0.0,53.0,53.0,1.3,1.0,3.0
6,531eb119-cab7-4ba9-8a25-489e91ec2a5a,3aa26fc8-4373-4387-ac50-4f7b0d417107,3aa26fc8-4373-4387-ac50-4f7b0d417107,Abarrotes vinos y licores La ranita,2022-11-10 18:31:16 UTC,2022-11-11 01:23:59 UTC,Sandra Carreón,Sandra Carreón,SRID=4326;POINT(-98.20348740564492 19.04590290...,0348df3f-5259-4d89-a718-46c32bd656f0,...,1,0,19.045903,-98.203487,0.0,8.0,8.0,1.0,1.0,3.0
7,17995e32-9ed3-4a27-8da3-b4e1d942ad36,5288fd44-2899-4765-9195-3f866d2e6d45,5288fd44-2899-4765-9195-3f866d2e6d45,Abarrotes vinos y licores La ranita,2022-11-11 04:30:19 UTC,2022-11-11 05:27:33 UTC,Sandra Carreón,Sandra Carreón,SRID=4326;POINT(-98.20328097193406 19.02348801...,eeddf981-d881-474d-b3a4-154d38765c43,...,1,0,19.023488,-98.203281,0.0,4.0,4.0,2.0,1.0,3.0
8,009bf340-321a-4739-84b4-d80029770d10,d1662ccd-4787-4c38-969a-a9e8a01ad1c2,d1662ccd-4787-4c38-969a-a9e8a01ad1c2,Mony,2022-11-11 22:44:44 UTC,2022-11-11 22:46:40 UTC,Sandra Carreón,Sandra Carreón,SRID=4326;POINT(-98.19369792680496 19.04645890...,9f1c577d-d44e-46c7-a12c-b8eb349ecf48,...,1,0,19.046459,-98.193698,0.0,116.0,116.0,2.0,1.0,2.0
9,c78336c3-d0ab-4e08-bc2e-f15af41f76fb,6f431744-a51b-4b36-b33f-13fb860ef131,6f431744-a51b-4b36-b33f-13fb860ef131,Tomales y molino Anita,2022-11-04 21:57:43 UTC,2022-11-04 22:11:37 UTC,José Varela,José Varela,SRID=4326;POINT(-98.3105623 19.0658682),c63f354b-3913-4716-bc54-f14b3b223b4c,...,1,0,19.065868,-98.310562,0.0,60.5,64.6,3.0,2.0,11.0
10,a616737c-bcb2-4ad0-a82a-4ca917fab0fc,56562b58-bfeb-4165-8e3b-7bc0a5a224cf,56562b58-bfeb-4165-8e3b-7bc0a5a224cf,La michoacana,2022-11-04 21:49:56 UTC,2022-11-04 21:52:44 UTC,José Varela,José Varela,SRID=4326;POINT(-98.3113028 19.0645079),c63f354b-3913-4716-bc54-f14b3b223b4c,...,1,0,19.064508,-98.311303,0.0,167.0,167.0,2.0,2.0,12.0
11,8e4d79db-4fa9-4c83-ba72-88b109a2a71b,af1d6ac9-3e31-42de-a4d2-873c080b8766,af1d6ac9-3e31-42de-a4d2-873c080b8766,Los globos,2022-11-10 17:33:57 UTC,2022-11-10 17:36:08 UTC,Sandra Carreón,Sandra Carreón,SRID=4326;POINT(-98.20425514008605 19.04738530...,0348df3f-5259-4d89-a718-46c32bd656f0,...,1,0,19.047385,-98.204255,0.0,130.0,130.0,1.3,1.0,5.0
12,89943c66-9129-458f-a295-6ecc61b4dfa2,9eac0dba-fb4b-4947-ba68-c406dadb6887,9eac0dba-fb4b-4947-ba68-c406dadb6887,Muebles Bustos,2022-11-10 16:26:45 UTC,2022-11-10 16:32:13 UTC,Sandra Carreón,Sandra Carreón,SRID=4326;POINT(-98.20005008882984 19.04881856...,0348df3f-5259-4d89-a718-46c32bd656f0,...,1,0,19.048819,-98.200050,0.0,11.0,11.0,0.0,1.0,4.3
13,044b47df-e630-4ca7-ac15-2ba322760aae,e3de2e0f-79f4-4698-a6e4-064aa921a5fb,e3de2e0f-79f4-4698-a6e4-064aa921a5fb,Gaspachos Morelianos,2022-11-10 17:35:22 UTC,2022-11-10 17:36:41 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.27405971141629 18.99942928...,e6356adb-d00a-4884-bf1c-ba51ad541c69,...,1,0,18.999429,-98.274060,0.0,78.0,78.0,1.0,3.0,8.0
14,98e21e5a-b7cc-4314-813e-b4cd016fbe67,75037107-c676-446a-ba1d-ab04881a6f67,75037107-c676-446a-ba1d-ab04881a6f67,Factory Blinds,2022-11-10 17:35:17 UTC,2022-11-10 17:36:04 UTC,José López,José López,SRID=4326;POINT(-98.27407890055497 18.99942571...,d12e4521-9723-4771-b5b2-b7cb56cf53e4,...,1,0,18.999426,-98.274079,0.0,46.0,46.0,2.0,1.0,2.0
15,eb6170a1-74f1-4dca-ba9b-53614e8ce1e9,3b3b959a-bc54-4825-8d79-f8e957a0355b,3b3b959a-bc54-4825-8d79-f8e957a0355b,Cabo San Lucas,2022-11-10 17:25:17 UTC,2022-11-10 17:26:07 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.26567356599786 19.00608812...,455ed590-a367-4fec-8d5c-c90516555fe2,...,1,0,19.006088,-98.265674,0.0,50.0,50.0,2.0,1.4,10.0
16,83fd3b7d-52b4-45d0-8f25-df98b6229aed,1464422d-78c5-4cfa-afa6-5bf569e882d2,1464422d-78c5-4cfa-afa6-5bf569e882d2,Postrecitos lindos,2022-11-10 17:21:02 UTC,2022-11-10 17:21:59 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.2656817442499 19.006137038...,d834689b-b029-41ea-874a-786e6deb0bfe,...,1,0,19.006137,-98.265682,0.0,56.0,56.0,0.0,2.0,6.0
17,e45b69e0-5250-403b-a1f4-54daf1427ff8,98008626-eea4-4f9a-ab80-de6e7c716207,98008626-eea4-4f9a-ab80-de6e7c716207,Stop by ramen,2022-11-10 17:20:56 UTC,2022-11-10 17:21:37 UTC,José López,José López,SRID=4326;POINT(-98.26567025179664 19.00611500...,81f1dcc0-9892-425f-a42c-bc9d3827524e,...,1,0,19.006115,-98.265670,0.0,41.0,41.0,0.0,1.0,2.0
18,7c0e3d41-b490-4940-8286-15fa3d8a5726,897dd608-be28-4337-b503-5dc70df1e2de,897dd608-be28-4337-b503-5dc70df1e2de,Súper boom,2022-11-10 17:11:09 UTC,2022-11-10 17:11:51 UTC,José López,José López,SRID=4326;POINT(-98.2665018576936 19.004100753...,2b18d917-7c1f-4e63-aa12-88f19203e347,...,1,0,19.004101,-98.266502,0.0,41.0,41.0,3.0,1.0,4.0
19,1788e007-9b6b-4cc4-aaf7-35d1b8143f32,f9dd984b-722a-4c26-aaef-d8ad2dff57b6,f9dd984b-722a-4c26-aaef-d8ad2dff57b6,Trípoli,2022-11-10 17:05:04 UTC,2022-11-10 17:06:25 UTC,José López,José López,SRID=4326;POINT(-98.2664907961389 19.004110110...,0d676fa7-0527-46e4-9804-7e22bbd87474,...,1,0,19.004110,-98.266491,0.0,81.0,81.0,2.0,1.0,2.0
20,c98cae40-7553-4755-a0f8-a51fbe275d12,94b03890-ef1b-4e87-bf0d-42bb64babb73,94b03890-ef1b-4e87-bf0d-42bb64babb73,La Medina,2022-11-10 17:01:02 UTC,2022-11-10 17:02:19 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.26618774968892 19.00450286...,1969525e-6664-4d85-b504-68e8e7235f31,...,1,0,19.004503,-98.266188,0.0,76.0,76.0,4.0,3.0,6.0
21,348702bf-ec37-436e-ba06-fe8e54abab13,0494e54e-1037-4788-9e37-b6bab949011b,0494e54e-1037-4788-9e37-b6bab949011b,Súper boom,2022-11-10 17:00:44 UTC,2022-11-10 17:01:25 UTC,José López,José López,SRID=4326;POINT(-98.26620398606103 19.00448073...,abb539b2-d33a-4b9c-a51e-fcaff8ff47f5,...,1,0,19.004481,-98.266204,0.0,40.0,40.0,4.0,2.0,5.0
22,383c55fc-f202-4a79-9425-eb7122d5e5e3,49b79862-d297-4391-bc6e-3e6d8b32d54a,49b79862-d297-4391-bc6e-3e6d8b32d54a,La Voila,2022-11-10 16:47:11 UTC,2022-11-10 16:48:20 UTC,José López,José López,SRID=4326;POINT(-98.27483802479486 18.99959829...,daf03321-dd07-47fc-9f3f-dfc6b098d7ab,...,1,0,18.999598,-98.274838,0.0,68.0,68.0,0.0,1.0,2.0
23,9b280ed5-61df-497d-8f64-7b847a08e0ea,be7db0e0-83ad-4486-aa8f-7d31402c2b92,be7db0e0-83ad-4486-aa8f-7d31402c2b92,Abastessen,2022-11-10 16:37:01 UTC,2022-11-10 16:38:01 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.27189571866822 19.00184227...,fecc2c99-9ba7-4af4-9e52-a943e0528b04,...,1,0,19.001842,-98.271896,0.0,60.0,60.0,0.0,2.0,5.0
24,17b5c8ed-6501-43bc-b16f-5008cdeb95d7,27bd6132-61df-496d-b780-9db89359dfc8,27bd6132-61df-496d-b780-9db89359dfc8,La central,2022-11-10 16:36:26 UTC,2022-11-10 16:37:10 UTC,José López,José López,SRID=4326;POINT(-98.27208717829416 19.00173048...,4d56086b-ac55-40e9-93f9-bfce5910928d,...,1,0,19.001730,-98.272087,0.0,43.0,43.0,2.0,1.0,2.0
25,1143e8d5-91ca-4d13-9a25-6f1b728bb91b,e648abf8-df90-46a2-af06-ee5d9662078d,e648abf8-df90-46a2-af06-ee5d9662078d,Súper Boom,2022-11-10 16:23:43 UTC,2022-11-10 16:25:17 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.26648594336065 19.00512008...,7032587e-d42b-402d-84b1-bf5341809da6,...,1,0,19.005120,-98.266486,0.0,94.0,94.0,1.0,2.0,3.0
26,b0f64dbe-1ef5-415a-a91a-c470c255b68d,cfb746bd-5e38-4361-9f45-be1af04f11da,cfb746bd-5e38-4361-9f45-be1af04f11da,Tripoli,2022-11-10 16:18:50 UTC,2022-11-10 16:19:47 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,SRID=4326;POINT(-98.26759626535545 19.00565243...,7c3ec9bd-d014-468c-8bad-0a6c7588dd9f,...,1,0,19.005652,-98.267596,0.0,57.0,57.0,0.0,2.0,4.0
27,f1c82664-47a4-480f-a242-bfa2d81c0d07,a626a0df-ca03-4bc9-b0c7-9d1df43daafa,a626a0df-ca03-4bc9-b0c7-9d1df43daafa,Nussett,2022-11-10 16:14:35 UTC,2022-11-10 16:16:12 UTC,José López,José López,SRID=4326;POINT(-98.26761701153431 19.00569198...,8ac023b6-3ac2-4286-98c5-60bf31e2d644,...,1,0,19.005692,-98.267617,0.0,97.0,97.0,0.0,1.0,4.0
28,613cb0b4-7aa9-478b-a8bd-f80b31ff18e4,119a1eaf-2d72-4792-94dd-23451e9daaec,119a1eaf-2d72-4792-94dd-23451e9daaec,Tamales Don Ignacio,2022-11-10 15:39:35 UTC,2022-11-10 15:41:17 UTC,José López,José López,SRID=4326;POINT(-98.26677136261554 19.00407882...,d694602e-4c1b-41a4-9a3c-c1153cd630b0,...,1,0,19.004079,-98.266771,0.0,2.0,2.0,1.0,0.0,2.0
29,e00ade25-e31b-410f-aed1-0aea780ea3ff,dda5dde0-71ac-4d49-a19d-f9194bf76666,dda5dde0-71ac-4d49-a19d-f9194bf76666,Aqua clyva,2022-11-09 22:02:13 UTC,2022-11-09 22:08:11 UTC,Juan Spínola,Juan Spínola,SRID=4326;POINT(-98.2493349482064 19.026688258...,ae8d67ce-c039-4118-8ab6-d1f8070d20bd,...,1,0,19.026688,-98.249335,0.0,60.5,64.6,0.0,1.0,2.0
30,7a620a44-774b-49ca-b340-b905328703d3,28a2af8e-8b1d-4acf-a077-0945049e826c,28a2af8e-8b1d-4acf-a077-0945049e826c,San Juditas,2022-11-09 22:14:50 UTC,2022-11-09 22:21:12 UTC,Luis Lara,Luis Lara,SRID=4326;POINT(-98.24903089562268 19.02517613...,92ae8e72-9eac-4976-a68d-512b1797498c,...,1,0,19.025176,-98.249031,0.0,60.5,64.6,3.0,1.0,4.0
31,871dc2b3-f27e-47c9-9e8e-cdc64650cd6c,1c566bed-bbc4-47a7-88d2-8d00dc535bcf,1c566bed-bbc4-47a7-88d2-8d00dc535bcf,Tecate,2022-11-09 20:51:52 UTC,2022-11-09 20:58:07 UTC,Luis Lara,Luis Lara,SRID=4326;POINT(-98.24979091394776 19.03083854...,cd5bc001-6630-4f06-aede-39db2c0e7346,...,1,0,19.030839,-98.249791,0.0,1.0,1.0,1.0,2.0,5.0
32,35f6404a-50cf-4064-84fa-0040c3abc3ad,8f7775ce-161e-47ae-8f03-063ecac52fc8,8f7775ce-161e-47ae-8f03-063ecac52fc8,Tecate,2022-11-09 20:50:07 UTC,2022-11-09 20:56:59 UTC,Juan Spínola,Juan Spínola,SRID=4326;POINT(-98.2499070999736 19.030742816...,908f4b9e-9c07-4cd7-a035-2dfc9f6294c8,...,1,0,19.030743,-98.249907,0.0,60.5,64.6,1.0,2.0,1.0
33,06f95065-77e8-4de8-9462-edfb34800898,227091c9-d136-428b-b0dd-f205f0675832,227091c9-d136-428b-b0dd-f205f0675832,San Juditas,2022-11-09 20:30:37 UTC,2022-11-09 20:33:26 UTC,Juan Spínola,Juan Spínola,SRID=4326;POINT(-98.2490547691168 19.025156034...,74298662-1842-41eb-ab88-0e0706b46d3b,...,1,0,19.025156,-98.249055,0.0,168.0,168.0,4.0,1.0,2.0
34,dd49ed79-b980-462e-98e7-d7abd6c1cbb4,ae8ea7eb-e3f3-4d44-926e-6205f04cf6e5,ae8ea7eb-e3f3-4d44-926e-6205f04cf6e5,Six,2022-11-09 18:01:35 UTC,2022-11-09 18:02:38 UTC,Diego Galicia Lugo,Diego Galicia Lugo,SRID=4326;POINT(-100.27416228457146 25.6095460...,43d78fa4-b706-4a98-80a0-3643fad22ee5,...,1,0,19.000000,-98.300000,0.0,62.0,62.0,0.0,1.0,1.0

In [63]:
valores_nulos=Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer.isnull().sum()
valores_nulos

_child_record_id                          0
_record_id                                0
_parent_id                                0
_title                                    0
_created_at                               0
_updated_at                               0
_created_by                               0
_updated_by                               0
_geometry                                 0
_changeset_id                             0
name_of_the_store                         0
entering_the_store                        0
picture_cargo_being_delivered             0
picture_cargo_being_delivered_captions    0
picture_cargo_being_delivered_urls        0
trolley_in_use                            0
leaving_the_store                         0
_version                                  0
_index                                    0
_latitude                                 0
_longitude                                0
_created_duration                         0
_updated_duration                         0
_edited_duration                          0
number_of_customers_in_store              0
number_of_suppliers_in_store              0
number_of_cases_boxes_delivered           0
dtype: int64

In [64]:
Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer.to_csv("Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer.csv")

In [65]:
from google.colab import files 
files.download("Datos_limpios_lastmile_delivery_operations_mit_lift_lab_serving_customer.csv")